name: Build and publish p-gen
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18.18'
          registry-url: 'https://registry.npmjs.org'
      - run: cd cli && yarn install --frozen-lockfile && yarn build
      - run: cd cli && npm config set //registry.npmjs.org/:_authToken ${NODE_AUTH_TOKEN} && yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
